// Copyright 2019-present Facebook Inc. All rights reserved.
// This source code is licensed under the Apache 2.0 license found
// in the LICENSE file in the root directory of this source tree.

// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"net"
	"net/http"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entc/integration/ent/fieldtype"
	"entgo.io/ent/entc/integration/ent/role"
	"entgo.io/ent/entc/integration/ent/schema"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// FieldTypeCreate is the builder for creating a FieldType entity.
type FieldTypeCreate struct {
	config
	mutation *FieldTypeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInt sets the "int" field.
func (ftc *FieldTypeCreate) SetInt(i int) *FieldTypeCreate {
	ftc.mutation.SetInt(i)
	return ftc
}

// SetInt8 sets the "int8" field.
func (ftc *FieldTypeCreate) SetInt8(i int8) *FieldTypeCreate {
	ftc.mutation.SetInt8(i)
	return ftc
}

// SetInt16 sets the "int16" field.
func (ftc *FieldTypeCreate) SetInt16(i int16) *FieldTypeCreate {
	ftc.mutation.SetInt16(i)
	return ftc
}

// SetInt32 sets the "int32" field.
func (ftc *FieldTypeCreate) SetInt32(i int32) *FieldTypeCreate {
	ftc.mutation.SetInt32(i)
	return ftc
}

// SetInt64 sets the "int64" field.
func (ftc *FieldTypeCreate) SetInt64(i int64) *FieldTypeCreate {
	ftc.mutation.SetInt64(i)
	return ftc
}

// SetOptionalInt sets the "optional_int" field.
func (ftc *FieldTypeCreate) SetOptionalInt(i int) *FieldTypeCreate {
	ftc.mutation.SetOptionalInt(i)
	return ftc
}

// SetNillableOptionalInt sets the "optional_int" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalInt(i *int) *FieldTypeCreate {
	if i != nil {
		ftc.SetOptionalInt(*i)
	}
	return ftc
}

// SetOptionalInt8 sets the "optional_int8" field.
func (ftc *FieldTypeCreate) SetOptionalInt8(i int8) *FieldTypeCreate {
	ftc.mutation.SetOptionalInt8(i)
	return ftc
}

// SetNillableOptionalInt8 sets the "optional_int8" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalInt8(i *int8) *FieldTypeCreate {
	if i != nil {
		ftc.SetOptionalInt8(*i)
	}
	return ftc
}

// SetOptionalInt16 sets the "optional_int16" field.
func (ftc *FieldTypeCreate) SetOptionalInt16(i int16) *FieldTypeCreate {
	ftc.mutation.SetOptionalInt16(i)
	return ftc
}

// SetNillableOptionalInt16 sets the "optional_int16" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalInt16(i *int16) *FieldTypeCreate {
	if i != nil {
		ftc.SetOptionalInt16(*i)
	}
	return ftc
}

// SetOptionalInt32 sets the "optional_int32" field.
func (ftc *FieldTypeCreate) SetOptionalInt32(i int32) *FieldTypeCreate {
	ftc.mutation.SetOptionalInt32(i)
	return ftc
}

// SetNillableOptionalInt32 sets the "optional_int32" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalInt32(i *int32) *FieldTypeCreate {
	if i != nil {
		ftc.SetOptionalInt32(*i)
	}
	return ftc
}

// SetOptionalInt64 sets the "optional_int64" field.
func (ftc *FieldTypeCreate) SetOptionalInt64(i int64) *FieldTypeCreate {
	ftc.mutation.SetOptionalInt64(i)
	return ftc
}

// SetNillableOptionalInt64 sets the "optional_int64" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalInt64(i *int64) *FieldTypeCreate {
	if i != nil {
		ftc.SetOptionalInt64(*i)
	}
	return ftc
}

// SetNillableInt sets the "nillable_int" field.
func (ftc *FieldTypeCreate) SetNillableInt(i int) *FieldTypeCreate {
	ftc.mutation.SetNillableInt(i)
	return ftc
}

// SetNillableNillableInt sets the "nillable_int" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableNillableInt(i *int) *FieldTypeCreate {
	if i != nil {
		ftc.SetNillableInt(*i)
	}
	return ftc
}

// SetNillableInt8 sets the "nillable_int8" field.
func (ftc *FieldTypeCreate) SetNillableInt8(i int8) *FieldTypeCreate {
	ftc.mutation.SetNillableInt8(i)
	return ftc
}

// SetNillableNillableInt8 sets the "nillable_int8" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableNillableInt8(i *int8) *FieldTypeCreate {
	if i != nil {
		ftc.SetNillableInt8(*i)
	}
	return ftc
}

// SetNillableInt16 sets the "nillable_int16" field.
func (ftc *FieldTypeCreate) SetNillableInt16(i int16) *FieldTypeCreate {
	ftc.mutation.SetNillableInt16(i)
	return ftc
}

// SetNillableNillableInt16 sets the "nillable_int16" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableNillableInt16(i *int16) *FieldTypeCreate {
	if i != nil {
		ftc.SetNillableInt16(*i)
	}
	return ftc
}

// SetNillableInt32 sets the "nillable_int32" field.
func (ftc *FieldTypeCreate) SetNillableInt32(i int32) *FieldTypeCreate {
	ftc.mutation.SetNillableInt32(i)
	return ftc
}

// SetNillableNillableInt32 sets the "nillable_int32" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableNillableInt32(i *int32) *FieldTypeCreate {
	if i != nil {
		ftc.SetNillableInt32(*i)
	}
	return ftc
}

// SetNillableInt64 sets the "nillable_int64" field.
func (ftc *FieldTypeCreate) SetNillableInt64(i int64) *FieldTypeCreate {
	ftc.mutation.SetNillableInt64(i)
	return ftc
}

// SetNillableNillableInt64 sets the "nillable_int64" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableNillableInt64(i *int64) *FieldTypeCreate {
	if i != nil {
		ftc.SetNillableInt64(*i)
	}
	return ftc
}

// SetValidateOptionalInt32 sets the "validate_optional_int32" field.
func (ftc *FieldTypeCreate) SetValidateOptionalInt32(i int32) *FieldTypeCreate {
	ftc.mutation.SetValidateOptionalInt32(i)
	return ftc
}

// SetNillableValidateOptionalInt32 sets the "validate_optional_int32" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableValidateOptionalInt32(i *int32) *FieldTypeCreate {
	if i != nil {
		ftc.SetValidateOptionalInt32(*i)
	}
	return ftc
}

// SetOptionalUint sets the "optional_uint" field.
func (ftc *FieldTypeCreate) SetOptionalUint(u uint) *FieldTypeCreate {
	ftc.mutation.SetOptionalUint(u)
	return ftc
}

// SetNillableOptionalUint sets the "optional_uint" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalUint(u *uint) *FieldTypeCreate {
	if u != nil {
		ftc.SetOptionalUint(*u)
	}
	return ftc
}

// SetOptionalUint8 sets the "optional_uint8" field.
func (ftc *FieldTypeCreate) SetOptionalUint8(u uint8) *FieldTypeCreate {
	ftc.mutation.SetOptionalUint8(u)
	return ftc
}

// SetNillableOptionalUint8 sets the "optional_uint8" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalUint8(u *uint8) *FieldTypeCreate {
	if u != nil {
		ftc.SetOptionalUint8(*u)
	}
	return ftc
}

// SetOptionalUint16 sets the "optional_uint16" field.
func (ftc *FieldTypeCreate) SetOptionalUint16(u uint16) *FieldTypeCreate {
	ftc.mutation.SetOptionalUint16(u)
	return ftc
}

// SetNillableOptionalUint16 sets the "optional_uint16" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalUint16(u *uint16) *FieldTypeCreate {
	if u != nil {
		ftc.SetOptionalUint16(*u)
	}
	return ftc
}

// SetOptionalUint32 sets the "optional_uint32" field.
func (ftc *FieldTypeCreate) SetOptionalUint32(u uint32) *FieldTypeCreate {
	ftc.mutation.SetOptionalUint32(u)
	return ftc
}

// SetNillableOptionalUint32 sets the "optional_uint32" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalUint32(u *uint32) *FieldTypeCreate {
	if u != nil {
		ftc.SetOptionalUint32(*u)
	}
	return ftc
}

// SetOptionalUint64 sets the "optional_uint64" field.
func (ftc *FieldTypeCreate) SetOptionalUint64(u uint64) *FieldTypeCreate {
	ftc.mutation.SetOptionalUint64(u)
	return ftc
}

// SetNillableOptionalUint64 sets the "optional_uint64" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalUint64(u *uint64) *FieldTypeCreate {
	if u != nil {
		ftc.SetOptionalUint64(*u)
	}
	return ftc
}

// SetState sets the "state" field.
func (ftc *FieldTypeCreate) SetState(f fieldtype.State) *FieldTypeCreate {
	ftc.mutation.SetState(f)
	return ftc
}

// SetNillableState sets the "state" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableState(f *fieldtype.State) *FieldTypeCreate {
	if f != nil {
		ftc.SetState(*f)
	}
	return ftc
}

// SetOptionalFloat sets the "optional_float" field.
func (ftc *FieldTypeCreate) SetOptionalFloat(f float64) *FieldTypeCreate {
	ftc.mutation.SetOptionalFloat(f)
	return ftc
}

// SetNillableOptionalFloat sets the "optional_float" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalFloat(f *float64) *FieldTypeCreate {
	if f != nil {
		ftc.SetOptionalFloat(*f)
	}
	return ftc
}

// SetOptionalFloat32 sets the "optional_float32" field.
func (ftc *FieldTypeCreate) SetOptionalFloat32(f float32) *FieldTypeCreate {
	ftc.mutation.SetOptionalFloat32(f)
	return ftc
}

// SetNillableOptionalFloat32 sets the "optional_float32" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableOptionalFloat32(f *float32) *FieldTypeCreate {
	if f != nil {
		ftc.SetOptionalFloat32(*f)
	}
	return ftc
}

// SetDatetime sets the "datetime" field.
func (ftc *FieldTypeCreate) SetDatetime(t time.Time) *FieldTypeCreate {
	ftc.mutation.SetDatetime(t)
	return ftc
}

// SetNillableDatetime sets the "datetime" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableDatetime(t *time.Time) *FieldTypeCreate {
	if t != nil {
		ftc.SetDatetime(*t)
	}
	return ftc
}

// SetDecimal sets the "decimal" field.
func (ftc *FieldTypeCreate) SetDecimal(f float64) *FieldTypeCreate {
	ftc.mutation.SetDecimal(f)
	return ftc
}

// SetNillableDecimal sets the "decimal" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableDecimal(f *float64) *FieldTypeCreate {
	if f != nil {
		ftc.SetDecimal(*f)
	}
	return ftc
}

// SetLinkOther sets the "link_other" field.
func (ftc *FieldTypeCreate) SetLinkOther(s *schema.Link) *FieldTypeCreate {
	ftc.mutation.SetLinkOther(s)
	return ftc
}

// SetMAC sets the "mac" field.
func (ftc *FieldTypeCreate) SetMAC(s schema.MAC) *FieldTypeCreate {
	ftc.mutation.SetMAC(s)
	return ftc
}

// SetNillableMAC sets the "mac" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableMAC(s *schema.MAC) *FieldTypeCreate {
	if s != nil {
		ftc.SetMAC(*s)
	}
	return ftc
}

// SetStringArray sets the "string_array" field.
func (ftc *FieldTypeCreate) SetStringArray(s schema.Strings) *FieldTypeCreate {
	ftc.mutation.SetStringArray(s)
	return ftc
}

// SetPassword sets the "password" field.
func (ftc *FieldTypeCreate) SetPassword(s string) *FieldTypeCreate {
	ftc.mutation.SetPassword(s)
	return ftc
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillablePassword(s *string) *FieldTypeCreate {
	if s != nil {
		ftc.SetPassword(*s)
	}
	return ftc
}

// SetStringScanner sets the "string_scanner" field.
func (ftc *FieldTypeCreate) SetStringScanner(ss schema.StringScanner) *FieldTypeCreate {
	ftc.mutation.SetStringScanner(ss)
	return ftc
}

// SetNillableStringScanner sets the "string_scanner" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableStringScanner(ss *schema.StringScanner) *FieldTypeCreate {
	if ss != nil {
		ftc.SetStringScanner(*ss)
	}
	return ftc
}

// SetDuration sets the "duration" field.
func (ftc *FieldTypeCreate) SetDuration(t time.Duration) *FieldTypeCreate {
	ftc.mutation.SetDuration(t)
	return ftc
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableDuration(t *time.Duration) *FieldTypeCreate {
	if t != nil {
		ftc.SetDuration(*t)
	}
	return ftc
}

// SetDir sets the "dir" field.
func (ftc *FieldTypeCreate) SetDir(h http.Dir) *FieldTypeCreate {
	ftc.mutation.SetDir(h)
	return ftc
}

// SetNillableDir sets the "dir" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableDir(h *http.Dir) *FieldTypeCreate {
	if h != nil {
		ftc.SetDir(*h)
	}
	return ftc
}

// SetNdir sets the "ndir" field.
func (ftc *FieldTypeCreate) SetNdir(h http.Dir) *FieldTypeCreate {
	ftc.mutation.SetNdir(h)
	return ftc
}

// SetNillableNdir sets the "ndir" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableNdir(h *http.Dir) *FieldTypeCreate {
	if h != nil {
		ftc.SetNdir(*h)
	}
	return ftc
}

// SetStr sets the "str" field.
func (ftc *FieldTypeCreate) SetStr(ss sql.NullString) *FieldTypeCreate {
	ftc.mutation.SetStr(ss)
	return ftc
}

// SetNillableStr sets the "str" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableStr(ss *sql.NullString) *FieldTypeCreate {
	if ss != nil {
		ftc.SetStr(*ss)
	}
	return ftc
}

// SetNullStr sets the "null_str" field.
func (ftc *FieldTypeCreate) SetNullStr(ss *sql.NullString) *FieldTypeCreate {
	ftc.mutation.SetNullStr(ss)
	return ftc
}

// SetLink sets the "link" field.
func (ftc *FieldTypeCreate) SetLink(s schema.Link) *FieldTypeCreate {
	ftc.mutation.SetLink(s)
	return ftc
}

// SetNillableLink sets the "link" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableLink(s *schema.Link) *FieldTypeCreate {
	if s != nil {
		ftc.SetLink(*s)
	}
	return ftc
}

// SetNullLink sets the "null_link" field.
func (ftc *FieldTypeCreate) SetNullLink(s *schema.Link) *FieldTypeCreate {
	ftc.mutation.SetNullLink(s)
	return ftc
}

// SetActive sets the "active" field.
func (ftc *FieldTypeCreate) SetActive(s schema.Status) *FieldTypeCreate {
	ftc.mutation.SetActive(s)
	return ftc
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableActive(s *schema.Status) *FieldTypeCreate {
	if s != nil {
		ftc.SetActive(*s)
	}
	return ftc
}

// SetNullActive sets the "null_active" field.
func (ftc *FieldTypeCreate) SetNullActive(s schema.Status) *FieldTypeCreate {
	ftc.mutation.SetNullActive(s)
	return ftc
}

// SetNillableNullActive sets the "null_active" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableNullActive(s *schema.Status) *FieldTypeCreate {
	if s != nil {
		ftc.SetNullActive(*s)
	}
	return ftc
}

// SetDeleted sets the "deleted" field.
func (ftc *FieldTypeCreate) SetDeleted(sb *sql.NullBool) *FieldTypeCreate {
	ftc.mutation.SetDeleted(sb)
	return ftc
}

// SetDeletedAt sets the "deleted_at" field.
func (ftc *FieldTypeCreate) SetDeletedAt(st *sql.NullTime) *FieldTypeCreate {
	ftc.mutation.SetDeletedAt(st)
	return ftc
}

// SetIP sets the "ip" field.
func (ftc *FieldTypeCreate) SetIP(n net.IP) *FieldTypeCreate {
	ftc.mutation.SetIP(n)
	return ftc
}

// SetNullInt64 sets the "null_int64" field.
func (ftc *FieldTypeCreate) SetNullInt64(si *sql.NullInt64) *FieldTypeCreate {
	ftc.mutation.SetNullInt64(si)
	return ftc
}

// SetSchemaInt sets the "schema_int" field.
func (ftc *FieldTypeCreate) SetSchemaInt(s schema.Int) *FieldTypeCreate {
	ftc.mutation.SetSchemaInt(s)
	return ftc
}

// SetNillableSchemaInt sets the "schema_int" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableSchemaInt(s *schema.Int) *FieldTypeCreate {
	if s != nil {
		ftc.SetSchemaInt(*s)
	}
	return ftc
}

// SetSchemaInt8 sets the "schema_int8" field.
func (ftc *FieldTypeCreate) SetSchemaInt8(s schema.Int8) *FieldTypeCreate {
	ftc.mutation.SetSchemaInt8(s)
	return ftc
}

// SetNillableSchemaInt8 sets the "schema_int8" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableSchemaInt8(s *schema.Int8) *FieldTypeCreate {
	if s != nil {
		ftc.SetSchemaInt8(*s)
	}
	return ftc
}

// SetSchemaInt64 sets the "schema_int64" field.
func (ftc *FieldTypeCreate) SetSchemaInt64(s schema.Int64) *FieldTypeCreate {
	ftc.mutation.SetSchemaInt64(s)
	return ftc
}

// SetNillableSchemaInt64 sets the "schema_int64" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableSchemaInt64(s *schema.Int64) *FieldTypeCreate {
	if s != nil {
		ftc.SetSchemaInt64(*s)
	}
	return ftc
}

// SetSchemaFloat sets the "schema_float" field.
func (ftc *FieldTypeCreate) SetSchemaFloat(s schema.Float64) *FieldTypeCreate {
	ftc.mutation.SetSchemaFloat(s)
	return ftc
}

// SetNillableSchemaFloat sets the "schema_float" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableSchemaFloat(s *schema.Float64) *FieldTypeCreate {
	if s != nil {
		ftc.SetSchemaFloat(*s)
	}
	return ftc
}

// SetSchemaFloat32 sets the "schema_float32" field.
func (ftc *FieldTypeCreate) SetSchemaFloat32(s schema.Float32) *FieldTypeCreate {
	ftc.mutation.SetSchemaFloat32(s)
	return ftc
}

// SetNillableSchemaFloat32 sets the "schema_float32" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableSchemaFloat32(s *schema.Float32) *FieldTypeCreate {
	if s != nil {
		ftc.SetSchemaFloat32(*s)
	}
	return ftc
}

// SetNullFloat sets the "null_float" field.
func (ftc *FieldTypeCreate) SetNullFloat(sf *sql.NullFloat64) *FieldTypeCreate {
	ftc.mutation.SetNullFloat(sf)
	return ftc
}

// SetRole sets the "role" field.
func (ftc *FieldTypeCreate) SetRole(r role.Role) *FieldTypeCreate {
	ftc.mutation.SetRole(r)
	return ftc
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableRole(r *role.Role) *FieldTypeCreate {
	if r != nil {
		ftc.SetRole(*r)
	}
	return ftc
}

// SetPriority sets the "priority" field.
func (ftc *FieldTypeCreate) SetPriority(r role.Priority) *FieldTypeCreate {
	ftc.mutation.SetPriority(r)
	return ftc
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillablePriority(r *role.Priority) *FieldTypeCreate {
	if r != nil {
		ftc.SetPriority(*r)
	}
	return ftc
}

// SetUUID sets the "uuid" field.
func (ftc *FieldTypeCreate) SetUUID(u uuid.UUID) *FieldTypeCreate {
	ftc.mutation.SetUUID(u)
	return ftc
}

// SetNillableUUID sets the "nillable_uuid" field.
func (ftc *FieldTypeCreate) SetNillableUUID(u uuid.UUID) *FieldTypeCreate {
	ftc.mutation.SetNillableUUID(u)
	return ftc
}

// SetStrings sets the "strings" field.
func (ftc *FieldTypeCreate) SetStrings(s []string) *FieldTypeCreate {
	ftc.mutation.SetStrings(s)
	return ftc
}

// SetPair sets the "pair" field.
func (ftc *FieldTypeCreate) SetPair(s schema.Pair) *FieldTypeCreate {
	ftc.mutation.SetPair(s)
	return ftc
}

// SetNillablePair sets the "pair" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillablePair(s *schema.Pair) *FieldTypeCreate {
	if s != nil {
		ftc.SetPair(*s)
	}
	return ftc
}

// SetNilPair sets the "nil_pair" field.
func (ftc *FieldTypeCreate) SetNilPair(s *schema.Pair) *FieldTypeCreate {
	ftc.mutation.SetNilPair(s)
	return ftc
}

// SetVstring sets the "vstring" field.
func (ftc *FieldTypeCreate) SetVstring(ss schema.VString) *FieldTypeCreate {
	ftc.mutation.SetVstring(ss)
	return ftc
}

// SetNillableVstring sets the "vstring" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableVstring(ss *schema.VString) *FieldTypeCreate {
	if ss != nil {
		ftc.SetVstring(*ss)
	}
	return ftc
}

// SetTriple sets the "triple" field.
func (ftc *FieldTypeCreate) SetTriple(s schema.Triple) *FieldTypeCreate {
	ftc.mutation.SetTriple(s)
	return ftc
}

// SetNillableTriple sets the "triple" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableTriple(s *schema.Triple) *FieldTypeCreate {
	if s != nil {
		ftc.SetTriple(*s)
	}
	return ftc
}

// SetBigInt sets the "big_int" field.
func (ftc *FieldTypeCreate) SetBigInt(si schema.BigInt) *FieldTypeCreate {
	ftc.mutation.SetBigInt(si)
	return ftc
}

// SetNillableBigInt sets the "big_int" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillableBigInt(si *schema.BigInt) *FieldTypeCreate {
	if si != nil {
		ftc.SetBigInt(*si)
	}
	return ftc
}

// SetPasswordOther sets the "password_other" field.
func (ftc *FieldTypeCreate) SetPasswordOther(s schema.Password) *FieldTypeCreate {
	ftc.mutation.SetPasswordOther(s)
	return ftc
}

// SetNillablePasswordOther sets the "password_other" field if the given value is not nil.
func (ftc *FieldTypeCreate) SetNillablePasswordOther(s *schema.Password) *FieldTypeCreate {
	if s != nil {
		ftc.SetPasswordOther(*s)
	}
	return ftc
}

// Mutation returns the FieldTypeMutation object of the builder.
func (ftc *FieldTypeCreate) Mutation() *FieldTypeMutation {
	return ftc.mutation
}

// Save creates the FieldType in the database.
func (ftc *FieldTypeCreate) Save(ctx context.Context) (*FieldType, error) {
	var (
		err  error
		node *FieldType
	)
	ftc.defaults()
	if len(ftc.hooks) == 0 {
		if err = ftc.check(); err != nil {
			return nil, err
		}
		node, err = ftc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FieldTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ftc.check(); err != nil {
				return nil, err
			}
			ftc.mutation = mutation
			if node, err = ftc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ftc.hooks) - 1; i >= 0; i-- {
			if ftc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ftc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ftc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ftc *FieldTypeCreate) SaveX(ctx context.Context) *FieldType {
	v, err := ftc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ftc *FieldTypeCreate) Exec(ctx context.Context) error {
	_, err := ftc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftc *FieldTypeCreate) ExecX(ctx context.Context) {
	if err := ftc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ftc *FieldTypeCreate) defaults() {
	if _, ok := ftc.mutation.Dir(); !ok {
		v := fieldtype.DefaultDir()
		ftc.mutation.SetDir(v)
	}
	if _, ok := ftc.mutation.Str(); !ok {
		v := fieldtype.DefaultStr()
		ftc.mutation.SetStr(v)
	}
	if _, ok := ftc.mutation.NullStr(); !ok {
		v := fieldtype.DefaultNullStr()
		ftc.mutation.SetNullStr(v)
	}
	if _, ok := ftc.mutation.IP(); !ok {
		v := fieldtype.DefaultIP()
		ftc.mutation.SetIP(v)
	}
	if _, ok := ftc.mutation.Role(); !ok {
		v := fieldtype.DefaultRole
		ftc.mutation.SetRole(v)
	}
	if _, ok := ftc.mutation.Pair(); !ok {
		v := fieldtype.DefaultPair()
		ftc.mutation.SetPair(v)
	}
	if _, ok := ftc.mutation.Vstring(); !ok {
		v := fieldtype.DefaultVstring()
		ftc.mutation.SetVstring(v)
	}
	if _, ok := ftc.mutation.Triple(); !ok {
		v := fieldtype.DefaultTriple()
		ftc.mutation.SetTriple(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ftc *FieldTypeCreate) check() error {
	if _, ok := ftc.mutation.Int(); !ok {
		return &ValidationError{Name: "int", err: errors.New(`ent: missing required field "int"`)}
	}
	if _, ok := ftc.mutation.Int8(); !ok {
		return &ValidationError{Name: "int8", err: errors.New(`ent: missing required field "int8"`)}
	}
	if _, ok := ftc.mutation.Int16(); !ok {
		return &ValidationError{Name: "int16", err: errors.New(`ent: missing required field "int16"`)}
	}
	if _, ok := ftc.mutation.Int32(); !ok {
		return &ValidationError{Name: "int32", err: errors.New(`ent: missing required field "int32"`)}
	}
	if _, ok := ftc.mutation.Int64(); !ok {
		return &ValidationError{Name: "int64", err: errors.New(`ent: missing required field "int64"`)}
	}
	if v, ok := ftc.mutation.ValidateOptionalInt32(); ok {
		if err := fieldtype.ValidateOptionalInt32Validator(v); err != nil {
			return &ValidationError{Name: "validate_optional_int32", err: fmt.Errorf(`ent: validator failed for field "validate_optional_int32": %w`, err)}
		}
	}
	if v, ok := ftc.mutation.State(); ok {
		if err := fieldtype.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "state": %w`, err)}
		}
	}
	if v, ok := ftc.mutation.MAC(); ok {
		if err := fieldtype.MACValidator(v.String()); err != nil {
			return &ValidationError{Name: "mac", err: fmt.Errorf(`ent: validator failed for field "mac": %w`, err)}
		}
	}
	if _, ok := ftc.mutation.Dir(); !ok {
		return &ValidationError{Name: "dir", err: errors.New(`ent: missing required field "dir"`)}
	}
	if v, ok := ftc.mutation.Ndir(); ok {
		if err := fieldtype.NdirValidator(string(v)); err != nil {
			return &ValidationError{Name: "ndir", err: fmt.Errorf(`ent: validator failed for field "ndir": %w`, err)}
		}
	}
	if v, ok := ftc.mutation.Link(); ok {
		if err := fieldtype.LinkValidator(v.String()); err != nil {
			return &ValidationError{Name: "link", err: fmt.Errorf(`ent: validator failed for field "link": %w`, err)}
		}
	}
	if v, ok := ftc.mutation.IP(); ok {
		if err := fieldtype.IPValidator([]byte(v)); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "ip": %w`, err)}
		}
	}
	if _, ok := ftc.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "role"`)}
	}
	if v, ok := ftc.mutation.Role(); ok {
		if err := fieldtype.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "role": %w`, err)}
		}
	}
	if v, ok := ftc.mutation.Priority(); ok {
		if err := fieldtype.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "priority": %w`, err)}
		}
	}
	if _, ok := ftc.mutation.Pair(); !ok {
		return &ValidationError{Name: "pair", err: errors.New(`ent: missing required field "pair"`)}
	}
	if _, ok := ftc.mutation.Vstring(); !ok {
		return &ValidationError{Name: "vstring", err: errors.New(`ent: missing required field "vstring"`)}
	}
	if _, ok := ftc.mutation.Triple(); !ok {
		return &ValidationError{Name: "triple", err: errors.New(`ent: missing required field "triple"`)}
	}
	return nil
}

func (ftc *FieldTypeCreate) sqlSave(ctx context.Context) (*FieldType, error) {
	_node, _spec := ftc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ftc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ftc *FieldTypeCreate) createSpec() (*FieldType, *sqlgraph.CreateSpec) {
	var (
		_node = &FieldType{config: ftc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: fieldtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: fieldtype.FieldID,
			},
		}
	)
	_spec.OnConflict = ftc.conflict
	if value, ok := ftc.mutation.Int(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: fieldtype.FieldInt,
		})
		_node.Int = value
	}
	if value, ok := ftc.mutation.Int8(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: fieldtype.FieldInt8,
		})
		_node.Int8 = value
	}
	if value, ok := ftc.mutation.Int16(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt16,
			Value:  value,
			Column: fieldtype.FieldInt16,
		})
		_node.Int16 = value
	}
	if value, ok := ftc.mutation.Int32(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: fieldtype.FieldInt32,
		})
		_node.Int32 = value
	}
	if value, ok := ftc.mutation.Int64(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: fieldtype.FieldInt64,
		})
		_node.Int64 = value
	}
	if value, ok := ftc.mutation.OptionalInt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: fieldtype.FieldOptionalInt,
		})
		_node.OptionalInt = value
	}
	if value, ok := ftc.mutation.OptionalInt8(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: fieldtype.FieldOptionalInt8,
		})
		_node.OptionalInt8 = value
	}
	if value, ok := ftc.mutation.OptionalInt16(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt16,
			Value:  value,
			Column: fieldtype.FieldOptionalInt16,
		})
		_node.OptionalInt16 = value
	}
	if value, ok := ftc.mutation.OptionalInt32(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: fieldtype.FieldOptionalInt32,
		})
		_node.OptionalInt32 = value
	}
	if value, ok := ftc.mutation.OptionalInt64(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: fieldtype.FieldOptionalInt64,
		})
		_node.OptionalInt64 = value
	}
	if value, ok := ftc.mutation.NillableInt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: fieldtype.FieldNillableInt,
		})
		_node.NillableInt = &value
	}
	if value, ok := ftc.mutation.NillableInt8(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: fieldtype.FieldNillableInt8,
		})
		_node.NillableInt8 = &value
	}
	if value, ok := ftc.mutation.NillableInt16(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt16,
			Value:  value,
			Column: fieldtype.FieldNillableInt16,
		})
		_node.NillableInt16 = &value
	}
	if value, ok := ftc.mutation.NillableInt32(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: fieldtype.FieldNillableInt32,
		})
		_node.NillableInt32 = &value
	}
	if value, ok := ftc.mutation.NillableInt64(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: fieldtype.FieldNillableInt64,
		})
		_node.NillableInt64 = &value
	}
	if value, ok := ftc.mutation.ValidateOptionalInt32(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt32,
			Value:  value,
			Column: fieldtype.FieldValidateOptionalInt32,
		})
		_node.ValidateOptionalInt32 = value
	}
	if value, ok := ftc.mutation.OptionalUint(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint,
			Value:  value,
			Column: fieldtype.FieldOptionalUint,
		})
		_node.OptionalUint = value
	}
	if value, ok := ftc.mutation.OptionalUint8(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint8,
			Value:  value,
			Column: fieldtype.FieldOptionalUint8,
		})
		_node.OptionalUint8 = value
	}
	if value, ok := ftc.mutation.OptionalUint16(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint16,
			Value:  value,
			Column: fieldtype.FieldOptionalUint16,
		})
		_node.OptionalUint16 = value
	}
	if value, ok := ftc.mutation.OptionalUint32(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint32,
			Value:  value,
			Column: fieldtype.FieldOptionalUint32,
		})
		_node.OptionalUint32 = value
	}
	if value, ok := ftc.mutation.OptionalUint64(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUint64,
			Value:  value,
			Column: fieldtype.FieldOptionalUint64,
		})
		_node.OptionalUint64 = value
	}
	if value, ok := ftc.mutation.State(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: fieldtype.FieldState,
		})
		_node.State = value
	}
	if value, ok := ftc.mutation.OptionalFloat(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: fieldtype.FieldOptionalFloat,
		})
		_node.OptionalFloat = value
	}
	if value, ok := ftc.mutation.OptionalFloat32(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat32,
			Value:  value,
			Column: fieldtype.FieldOptionalFloat32,
		})
		_node.OptionalFloat32 = value
	}
	if value, ok := ftc.mutation.Datetime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: fieldtype.FieldDatetime,
		})
		_node.Datetime = value
	}
	if value, ok := ftc.mutation.Decimal(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: fieldtype.FieldDecimal,
		})
		_node.Decimal = value
	}
	if value, ok := ftc.mutation.LinkOther(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: fieldtype.FieldLinkOther,
		})
		_node.LinkOther = value
	}
	if value, ok := ftc.mutation.MAC(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldMAC,
		})
		_node.MAC = value
	}
	if value, ok := ftc.mutation.StringArray(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: fieldtype.FieldStringArray,
		})
		_node.StringArray = value
	}
	if value, ok := ftc.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldPassword,
		})
		_node.Password = value
	}
	if value, ok := ftc.mutation.StringScanner(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldStringScanner,
		})
		_node.StringScanner = &value
	}
	if value, ok := ftc.mutation.Duration(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: fieldtype.FieldDuration,
		})
		_node.Duration = value
	}
	if value, ok := ftc.mutation.Dir(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldDir,
		})
		_node.Dir = value
	}
	if value, ok := ftc.mutation.Ndir(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldNdir,
		})
		_node.Ndir = &value
	}
	if value, ok := ftc.mutation.Str(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldStr,
		})
		_node.Str = value
	}
	if value, ok := ftc.mutation.NullStr(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldNullStr,
		})
		_node.NullStr = value
	}
	if value, ok := ftc.mutation.Link(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldLink,
		})
		_node.Link = value
	}
	if value, ok := ftc.mutation.NullLink(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldNullLink,
		})
		_node.NullLink = value
	}
	if value, ok := ftc.mutation.Active(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: fieldtype.FieldActive,
		})
		_node.Active = value
	}
	if value, ok := ftc.mutation.NullActive(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: fieldtype.FieldNullActive,
		})
		_node.NullActive = &value
	}
	if value, ok := ftc.mutation.Deleted(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: fieldtype.FieldDeleted,
		})
		_node.Deleted = value
	}
	if value, ok := ftc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: fieldtype.FieldDeletedAt,
		})
		_node.DeletedAt = value
	}
	if value, ok := ftc.mutation.IP(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: fieldtype.FieldIP,
		})
		_node.IP = value
	}
	if value, ok := ftc.mutation.NullInt64(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: fieldtype.FieldNullInt64,
		})
		_node.NullInt64 = value
	}
	if value, ok := ftc.mutation.SchemaInt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: fieldtype.FieldSchemaInt,
		})
		_node.SchemaInt = value
	}
	if value, ok := ftc.mutation.SchemaInt8(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt8,
			Value:  value,
			Column: fieldtype.FieldSchemaInt8,
		})
		_node.SchemaInt8 = value
	}
	if value, ok := ftc.mutation.SchemaInt64(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt64,
			Value:  value,
			Column: fieldtype.FieldSchemaInt64,
		})
		_node.SchemaInt64 = value
	}
	if value, ok := ftc.mutation.SchemaFloat(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: fieldtype.FieldSchemaFloat,
		})
		_node.SchemaFloat = value
	}
	if value, ok := ftc.mutation.SchemaFloat32(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat32,
			Value:  value,
			Column: fieldtype.FieldSchemaFloat32,
		})
		_node.SchemaFloat32 = value
	}
	if value, ok := ftc.mutation.NullFloat(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeFloat64,
			Value:  value,
			Column: fieldtype.FieldNullFloat,
		})
		_node.NullFloat = value
	}
	if value, ok := ftc.mutation.Role(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: fieldtype.FieldRole,
		})
		_node.Role = value
	}
	if value, ok := ftc.mutation.Priority(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: fieldtype.FieldPriority,
		})
		_node.Priority = value
	}
	if value, ok := ftc.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: fieldtype.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := ftc.mutation.NillableUUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: fieldtype.FieldNillableUUID,
		})
		_node.NillableUUID = &value
	}
	if value, ok := ftc.mutation.Strings(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: fieldtype.FieldStrings,
		})
		_node.Strings = value
	}
	if value, ok := ftc.mutation.Pair(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: fieldtype.FieldPair,
		})
		_node.Pair = value
	}
	if value, ok := ftc.mutation.NilPair(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: fieldtype.FieldNilPair,
		})
		_node.NilPair = value
	}
	if value, ok := ftc.mutation.Vstring(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldVstring,
		})
		_node.Vstring = value
	}
	if value, ok := ftc.mutation.Triple(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: fieldtype.FieldTriple,
		})
		_node.Triple = value
	}
	if value, ok := ftc.mutation.BigInt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: fieldtype.FieldBigInt,
		})
		_node.BigInt = value
	}
	if value, ok := ftc.mutation.PasswordOther(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeOther,
			Value:  value,
			Column: fieldtype.FieldPasswordOther,
		})
		_node.PasswordOther = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FieldType.Create().
//		SetInt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//      // Override some of the fields with custom
//      // update values.
//		Update(func(u *ent.UserUpsert) {
//			SetInt(v+v).
//		}).
//      Exec(ctx)
//
func (ftc *FieldTypeCreate) OnConflict(opts ...sql.ConflictOption) *FieldTypeUpsertOne {
	ftc.conflict = opts
	return &FieldTypeUpsertOne{
		create: ftc,
	}
}

type (
	// FieldTypeUpsertOne is the builder for "upsert"-ing
	//  one FieldType node.
	FieldTypeUpsertOne struct {
		create *FieldTypeCreate
	}

	// FieldTypeUpsert is the "OnConflict" setter.
	FieldTypeUpsert struct {
		*sql.UpdateSet
	}
)

// SetInt sets the "int" field.
func (u *FieldTypeUpsert) SetInt(v int) *FieldTypeUpsert {
	u.Set(fieldtype.FieldInt, v)
	return u
}

// SetNewInt sets the "int" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewInt() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldInt)
	return u
}

// SetInt8 sets the "int8" field.
func (u *FieldTypeUpsert) SetInt8(v int8) *FieldTypeUpsert {
	u.Set(fieldtype.FieldInt8, v)
	return u
}

// SetNewInt8 sets the "int8" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewInt8() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldInt8)
	return u
}

// SetInt16 sets the "int16" field.
func (u *FieldTypeUpsert) SetInt16(v int16) *FieldTypeUpsert {
	u.Set(fieldtype.FieldInt16, v)
	return u
}

// SetNewInt16 sets the "int16" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewInt16() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldInt16)
	return u
}

// SetInt32 sets the "int32" field.
func (u *FieldTypeUpsert) SetInt32(v int32) *FieldTypeUpsert {
	u.Set(fieldtype.FieldInt32, v)
	return u
}

// SetNewInt32 sets the "int32" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewInt32() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldInt32)
	return u
}

// SetInt64 sets the "int64" field.
func (u *FieldTypeUpsert) SetInt64(v int64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldInt64, v)
	return u
}

// SetNewInt64 sets the "int64" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewInt64() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldInt64)
	return u
}

// SetOptionalInt sets the "optional_int" field.
func (u *FieldTypeUpsert) SetOptionalInt(v int) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalInt, v)
	return u
}

// SetNewOptionalInt sets the "optional_int" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalInt() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalInt)
	return u
}

// ClearOptionalInt clears the value of the "optional_int" field.
func (u *FieldTypeUpsert) ClearOptionalInt() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalInt)
	return u
}

// SetOptionalInt8 sets the "optional_int8" field.
func (u *FieldTypeUpsert) SetOptionalInt8(v int8) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalInt8, v)
	return u
}

// SetNewOptionalInt8 sets the "optional_int8" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalInt8() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalInt8)
	return u
}

// ClearOptionalInt8 clears the value of the "optional_int8" field.
func (u *FieldTypeUpsert) ClearOptionalInt8() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalInt8)
	return u
}

// SetOptionalInt16 sets the "optional_int16" field.
func (u *FieldTypeUpsert) SetOptionalInt16(v int16) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalInt16, v)
	return u
}

// SetNewOptionalInt16 sets the "optional_int16" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalInt16() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalInt16)
	return u
}

// ClearOptionalInt16 clears the value of the "optional_int16" field.
func (u *FieldTypeUpsert) ClearOptionalInt16() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalInt16)
	return u
}

// SetOptionalInt32 sets the "optional_int32" field.
func (u *FieldTypeUpsert) SetOptionalInt32(v int32) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalInt32, v)
	return u
}

// SetNewOptionalInt32 sets the "optional_int32" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalInt32() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalInt32)
	return u
}

// ClearOptionalInt32 clears the value of the "optional_int32" field.
func (u *FieldTypeUpsert) ClearOptionalInt32() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalInt32)
	return u
}

// SetOptionalInt64 sets the "optional_int64" field.
func (u *FieldTypeUpsert) SetOptionalInt64(v int64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalInt64, v)
	return u
}

// SetNewOptionalInt64 sets the "optional_int64" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalInt64() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalInt64)
	return u
}

// ClearOptionalInt64 clears the value of the "optional_int64" field.
func (u *FieldTypeUpsert) ClearOptionalInt64() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalInt64)
	return u
}

// SetNillableInt sets the "nillable_int" field.
func (u *FieldTypeUpsert) SetNillableInt(v int) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNillableInt, v)
	return u
}

// SetNewNillableInt sets the "nillable_int" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNillableInt() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNillableInt)
	return u
}

// ClearNillableInt clears the value of the "nillable_int" field.
func (u *FieldTypeUpsert) ClearNillableInt() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNillableInt)
	return u
}

// SetNillableInt8 sets the "nillable_int8" field.
func (u *FieldTypeUpsert) SetNillableInt8(v int8) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNillableInt8, v)
	return u
}

// SetNewNillableInt8 sets the "nillable_int8" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNillableInt8() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNillableInt8)
	return u
}

// ClearNillableInt8 clears the value of the "nillable_int8" field.
func (u *FieldTypeUpsert) ClearNillableInt8() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNillableInt8)
	return u
}

// SetNillableInt16 sets the "nillable_int16" field.
func (u *FieldTypeUpsert) SetNillableInt16(v int16) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNillableInt16, v)
	return u
}

// SetNewNillableInt16 sets the "nillable_int16" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNillableInt16() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNillableInt16)
	return u
}

// ClearNillableInt16 clears the value of the "nillable_int16" field.
func (u *FieldTypeUpsert) ClearNillableInt16() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNillableInt16)
	return u
}

// SetNillableInt32 sets the "nillable_int32" field.
func (u *FieldTypeUpsert) SetNillableInt32(v int32) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNillableInt32, v)
	return u
}

// SetNewNillableInt32 sets the "nillable_int32" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNillableInt32() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNillableInt32)
	return u
}

// ClearNillableInt32 clears the value of the "nillable_int32" field.
func (u *FieldTypeUpsert) ClearNillableInt32() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNillableInt32)
	return u
}

// SetNillableInt64 sets the "nillable_int64" field.
func (u *FieldTypeUpsert) SetNillableInt64(v int64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNillableInt64, v)
	return u
}

// SetNewNillableInt64 sets the "nillable_int64" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNillableInt64() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNillableInt64)
	return u
}

// ClearNillableInt64 clears the value of the "nillable_int64" field.
func (u *FieldTypeUpsert) ClearNillableInt64() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNillableInt64)
	return u
}

// SetValidateOptionalInt32 sets the "validate_optional_int32" field.
func (u *FieldTypeUpsert) SetValidateOptionalInt32(v int32) *FieldTypeUpsert {
	u.Set(fieldtype.FieldValidateOptionalInt32, v)
	return u
}

// SetNewValidateOptionalInt32 sets the "validate_optional_int32" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewValidateOptionalInt32() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldValidateOptionalInt32)
	return u
}

// ClearValidateOptionalInt32 clears the value of the "validate_optional_int32" field.
func (u *FieldTypeUpsert) ClearValidateOptionalInt32() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldValidateOptionalInt32)
	return u
}

// SetOptionalUint sets the "optional_uint" field.
func (u *FieldTypeUpsert) SetOptionalUint(v uint) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalUint, v)
	return u
}

// SetNewOptionalUint sets the "optional_uint" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalUint() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalUint)
	return u
}

// ClearOptionalUint clears the value of the "optional_uint" field.
func (u *FieldTypeUpsert) ClearOptionalUint() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalUint)
	return u
}

// SetOptionalUint8 sets the "optional_uint8" field.
func (u *FieldTypeUpsert) SetOptionalUint8(v uint8) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalUint8, v)
	return u
}

// SetNewOptionalUint8 sets the "optional_uint8" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalUint8() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalUint8)
	return u
}

// ClearOptionalUint8 clears the value of the "optional_uint8" field.
func (u *FieldTypeUpsert) ClearOptionalUint8() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalUint8)
	return u
}

// SetOptionalUint16 sets the "optional_uint16" field.
func (u *FieldTypeUpsert) SetOptionalUint16(v uint16) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalUint16, v)
	return u
}

// SetNewOptionalUint16 sets the "optional_uint16" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalUint16() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalUint16)
	return u
}

// ClearOptionalUint16 clears the value of the "optional_uint16" field.
func (u *FieldTypeUpsert) ClearOptionalUint16() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalUint16)
	return u
}

// SetOptionalUint32 sets the "optional_uint32" field.
func (u *FieldTypeUpsert) SetOptionalUint32(v uint32) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalUint32, v)
	return u
}

// SetNewOptionalUint32 sets the "optional_uint32" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalUint32() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalUint32)
	return u
}

// ClearOptionalUint32 clears the value of the "optional_uint32" field.
func (u *FieldTypeUpsert) ClearOptionalUint32() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalUint32)
	return u
}

// SetOptionalUint64 sets the "optional_uint64" field.
func (u *FieldTypeUpsert) SetOptionalUint64(v uint64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalUint64, v)
	return u
}

// SetNewOptionalUint64 sets the "optional_uint64" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalUint64() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalUint64)
	return u
}

// ClearOptionalUint64 clears the value of the "optional_uint64" field.
func (u *FieldTypeUpsert) ClearOptionalUint64() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalUint64)
	return u
}

// SetState sets the "state" field.
func (u *FieldTypeUpsert) SetState(v fieldtype.State) *FieldTypeUpsert {
	u.Set(fieldtype.FieldState, v)
	return u
}

// SetNewState sets the "state" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewState() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldState)
	return u
}

// ClearState clears the value of the "state" field.
func (u *FieldTypeUpsert) ClearState() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldState)
	return u
}

// SetOptionalFloat sets the "optional_float" field.
func (u *FieldTypeUpsert) SetOptionalFloat(v float64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalFloat, v)
	return u
}

// SetNewOptionalFloat sets the "optional_float" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalFloat() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalFloat)
	return u
}

// ClearOptionalFloat clears the value of the "optional_float" field.
func (u *FieldTypeUpsert) ClearOptionalFloat() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalFloat)
	return u
}

// SetOptionalFloat32 sets the "optional_float32" field.
func (u *FieldTypeUpsert) SetOptionalFloat32(v float32) *FieldTypeUpsert {
	u.Set(fieldtype.FieldOptionalFloat32, v)
	return u
}

// SetNewOptionalFloat32 sets the "optional_float32" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewOptionalFloat32() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldOptionalFloat32)
	return u
}

// ClearOptionalFloat32 clears the value of the "optional_float32" field.
func (u *FieldTypeUpsert) ClearOptionalFloat32() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldOptionalFloat32)
	return u
}

// SetDatetime sets the "datetime" field.
func (u *FieldTypeUpsert) SetDatetime(v time.Time) *FieldTypeUpsert {
	u.Set(fieldtype.FieldDatetime, v)
	return u
}

// SetNewDatetime sets the "datetime" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewDatetime() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldDatetime)
	return u
}

// ClearDatetime clears the value of the "datetime" field.
func (u *FieldTypeUpsert) ClearDatetime() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldDatetime)
	return u
}

// SetDecimal sets the "decimal" field.
func (u *FieldTypeUpsert) SetDecimal(v float64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldDecimal, v)
	return u
}

// SetNewDecimal sets the "decimal" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewDecimal() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldDecimal)
	return u
}

// ClearDecimal clears the value of the "decimal" field.
func (u *FieldTypeUpsert) ClearDecimal() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldDecimal)
	return u
}

// SetLinkOther sets the "link_other" field.
func (u *FieldTypeUpsert) SetLinkOther(v *schema.Link) *FieldTypeUpsert {
	u.Set(fieldtype.FieldLinkOther, v)
	return u
}

// SetNewLinkOther sets the "link_other" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewLinkOther() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldLinkOther)
	return u
}

// ClearLinkOther clears the value of the "link_other" field.
func (u *FieldTypeUpsert) ClearLinkOther() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldLinkOther)
	return u
}

// SetMAC sets the "mac" field.
func (u *FieldTypeUpsert) SetMAC(v schema.MAC) *FieldTypeUpsert {
	u.Set(fieldtype.FieldMAC, v)
	return u
}

// SetNewMAC sets the "mac" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewMAC() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldMAC)
	return u
}

// ClearMAC clears the value of the "mac" field.
func (u *FieldTypeUpsert) ClearMAC() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldMAC)
	return u
}

// SetStringArray sets the "string_array" field.
func (u *FieldTypeUpsert) SetStringArray(v schema.Strings) *FieldTypeUpsert {
	u.Set(fieldtype.FieldStringArray, v)
	return u
}

// SetNewStringArray sets the "string_array" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewStringArray() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldStringArray)
	return u
}

// ClearStringArray clears the value of the "string_array" field.
func (u *FieldTypeUpsert) ClearStringArray() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldStringArray)
	return u
}

// SetPassword sets the "password" field.
func (u *FieldTypeUpsert) SetPassword(v string) *FieldTypeUpsert {
	u.Set(fieldtype.FieldPassword, v)
	return u
}

// SetNewPassword sets the "password" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewPassword() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldPassword)
	return u
}

// ClearPassword clears the value of the "password" field.
func (u *FieldTypeUpsert) ClearPassword() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldPassword)
	return u
}

// SetStringScanner sets the "string_scanner" field.
func (u *FieldTypeUpsert) SetStringScanner(v schema.StringScanner) *FieldTypeUpsert {
	u.Set(fieldtype.FieldStringScanner, v)
	return u
}

// SetNewStringScanner sets the "string_scanner" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewStringScanner() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldStringScanner)
	return u
}

// ClearStringScanner clears the value of the "string_scanner" field.
func (u *FieldTypeUpsert) ClearStringScanner() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldStringScanner)
	return u
}

// SetDuration sets the "duration" field.
func (u *FieldTypeUpsert) SetDuration(v time.Duration) *FieldTypeUpsert {
	u.Set(fieldtype.FieldDuration, v)
	return u
}

// SetNewDuration sets the "duration" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewDuration() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldDuration)
	return u
}

// ClearDuration clears the value of the "duration" field.
func (u *FieldTypeUpsert) ClearDuration() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldDuration)
	return u
}

// SetDir sets the "dir" field.
func (u *FieldTypeUpsert) SetDir(v http.Dir) *FieldTypeUpsert {
	u.Set(fieldtype.FieldDir, v)
	return u
}

// SetNewDir sets the "dir" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewDir() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldDir)
	return u
}

// SetNdir sets the "ndir" field.
func (u *FieldTypeUpsert) SetNdir(v http.Dir) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNdir, v)
	return u
}

// SetNewNdir sets the "ndir" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNdir() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNdir)
	return u
}

// ClearNdir clears the value of the "ndir" field.
func (u *FieldTypeUpsert) ClearNdir() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNdir)
	return u
}

// SetStr sets the "str" field.
func (u *FieldTypeUpsert) SetStr(v sql.NullString) *FieldTypeUpsert {
	u.Set(fieldtype.FieldStr, v)
	return u
}

// SetNewStr sets the "str" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewStr() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldStr)
	return u
}

// ClearStr clears the value of the "str" field.
func (u *FieldTypeUpsert) ClearStr() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldStr)
	return u
}

// SetNullStr sets the "null_str" field.
func (u *FieldTypeUpsert) SetNullStr(v *sql.NullString) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNullStr, v)
	return u
}

// SetNewNullStr sets the "null_str" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNullStr() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNullStr)
	return u
}

// ClearNullStr clears the value of the "null_str" field.
func (u *FieldTypeUpsert) ClearNullStr() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNullStr)
	return u
}

// SetLink sets the "link" field.
func (u *FieldTypeUpsert) SetLink(v schema.Link) *FieldTypeUpsert {
	u.Set(fieldtype.FieldLink, v)
	return u
}

// SetNewLink sets the "link" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewLink() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldLink)
	return u
}

// ClearLink clears the value of the "link" field.
func (u *FieldTypeUpsert) ClearLink() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldLink)
	return u
}

// SetNullLink sets the "null_link" field.
func (u *FieldTypeUpsert) SetNullLink(v *schema.Link) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNullLink, v)
	return u
}

// SetNewNullLink sets the "null_link" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNullLink() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNullLink)
	return u
}

// ClearNullLink clears the value of the "null_link" field.
func (u *FieldTypeUpsert) ClearNullLink() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNullLink)
	return u
}

// SetActive sets the "active" field.
func (u *FieldTypeUpsert) SetActive(v schema.Status) *FieldTypeUpsert {
	u.Set(fieldtype.FieldActive, v)
	return u
}

// SetNewActive sets the "active" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewActive() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldActive)
	return u
}

// ClearActive clears the value of the "active" field.
func (u *FieldTypeUpsert) ClearActive() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldActive)
	return u
}

// SetNullActive sets the "null_active" field.
func (u *FieldTypeUpsert) SetNullActive(v schema.Status) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNullActive, v)
	return u
}

// SetNewNullActive sets the "null_active" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNullActive() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNullActive)
	return u
}

// ClearNullActive clears the value of the "null_active" field.
func (u *FieldTypeUpsert) ClearNullActive() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNullActive)
	return u
}

// SetDeleted sets the "deleted" field.
func (u *FieldTypeUpsert) SetDeleted(v *sql.NullBool) *FieldTypeUpsert {
	u.Set(fieldtype.FieldDeleted, v)
	return u
}

// SetNewDeleted sets the "deleted" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewDeleted() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldDeleted)
	return u
}

// ClearDeleted clears the value of the "deleted" field.
func (u *FieldTypeUpsert) ClearDeleted() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldDeleted)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *FieldTypeUpsert) SetDeletedAt(v *sql.NullTime) *FieldTypeUpsert {
	u.Set(fieldtype.FieldDeletedAt, v)
	return u
}

// SetNewDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewDeletedAt() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *FieldTypeUpsert) ClearDeletedAt() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldDeletedAt)
	return u
}

// SetIP sets the "ip" field.
func (u *FieldTypeUpsert) SetIP(v net.IP) *FieldTypeUpsert {
	u.Set(fieldtype.FieldIP, v)
	return u
}

// SetNewIP sets the "ip" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewIP() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *FieldTypeUpsert) ClearIP() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldIP)
	return u
}

// SetNullInt64 sets the "null_int64" field.
func (u *FieldTypeUpsert) SetNullInt64(v *sql.NullInt64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNullInt64, v)
	return u
}

// SetNewNullInt64 sets the "null_int64" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNullInt64() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNullInt64)
	return u
}

// ClearNullInt64 clears the value of the "null_int64" field.
func (u *FieldTypeUpsert) ClearNullInt64() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNullInt64)
	return u
}

// SetSchemaInt sets the "schema_int" field.
func (u *FieldTypeUpsert) SetSchemaInt(v schema.Int) *FieldTypeUpsert {
	u.Set(fieldtype.FieldSchemaInt, v)
	return u
}

// SetNewSchemaInt sets the "schema_int" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewSchemaInt() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldSchemaInt)
	return u
}

// ClearSchemaInt clears the value of the "schema_int" field.
func (u *FieldTypeUpsert) ClearSchemaInt() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldSchemaInt)
	return u
}

// SetSchemaInt8 sets the "schema_int8" field.
func (u *FieldTypeUpsert) SetSchemaInt8(v schema.Int8) *FieldTypeUpsert {
	u.Set(fieldtype.FieldSchemaInt8, v)
	return u
}

// SetNewSchemaInt8 sets the "schema_int8" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewSchemaInt8() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldSchemaInt8)
	return u
}

// ClearSchemaInt8 clears the value of the "schema_int8" field.
func (u *FieldTypeUpsert) ClearSchemaInt8() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldSchemaInt8)
	return u
}

// SetSchemaInt64 sets the "schema_int64" field.
func (u *FieldTypeUpsert) SetSchemaInt64(v schema.Int64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldSchemaInt64, v)
	return u
}

// SetNewSchemaInt64 sets the "schema_int64" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewSchemaInt64() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldSchemaInt64)
	return u
}

// ClearSchemaInt64 clears the value of the "schema_int64" field.
func (u *FieldTypeUpsert) ClearSchemaInt64() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldSchemaInt64)
	return u
}

// SetSchemaFloat sets the "schema_float" field.
func (u *FieldTypeUpsert) SetSchemaFloat(v schema.Float64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldSchemaFloat, v)
	return u
}

// SetNewSchemaFloat sets the "schema_float" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewSchemaFloat() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldSchemaFloat)
	return u
}

// ClearSchemaFloat clears the value of the "schema_float" field.
func (u *FieldTypeUpsert) ClearSchemaFloat() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldSchemaFloat)
	return u
}

// SetSchemaFloat32 sets the "schema_float32" field.
func (u *FieldTypeUpsert) SetSchemaFloat32(v schema.Float32) *FieldTypeUpsert {
	u.Set(fieldtype.FieldSchemaFloat32, v)
	return u
}

// SetNewSchemaFloat32 sets the "schema_float32" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewSchemaFloat32() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldSchemaFloat32)
	return u
}

// ClearSchemaFloat32 clears the value of the "schema_float32" field.
func (u *FieldTypeUpsert) ClearSchemaFloat32() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldSchemaFloat32)
	return u
}

// SetNullFloat sets the "null_float" field.
func (u *FieldTypeUpsert) SetNullFloat(v *sql.NullFloat64) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNullFloat, v)
	return u
}

// SetNewNullFloat sets the "null_float" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNullFloat() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNullFloat)
	return u
}

// ClearNullFloat clears the value of the "null_float" field.
func (u *FieldTypeUpsert) ClearNullFloat() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNullFloat)
	return u
}

// SetRole sets the "role" field.
func (u *FieldTypeUpsert) SetRole(v role.Role) *FieldTypeUpsert {
	u.Set(fieldtype.FieldRole, v)
	return u
}

// SetNewRole sets the "role" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewRole() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldRole)
	return u
}

// SetPriority sets the "priority" field.
func (u *FieldTypeUpsert) SetPriority(v role.Priority) *FieldTypeUpsert {
	u.Set(fieldtype.FieldPriority, v)
	return u
}

// SetNewPriority sets the "priority" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewPriority() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldPriority)
	return u
}

// ClearPriority clears the value of the "priority" field.
func (u *FieldTypeUpsert) ClearPriority() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldPriority)
	return u
}

// SetUUID sets the "uuid" field.
func (u *FieldTypeUpsert) SetUUID(v uuid.UUID) *FieldTypeUpsert {
	u.Set(fieldtype.FieldUUID, v)
	return u
}

// SetNewUUID sets the "uuid" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewUUID() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldUUID)
	return u
}

// ClearUUID clears the value of the "uuid" field.
func (u *FieldTypeUpsert) ClearUUID() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldUUID)
	return u
}

// SetNillableUUID sets the "nillable_uuid" field.
func (u *FieldTypeUpsert) SetNillableUUID(v uuid.UUID) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNillableUUID, v)
	return u
}

// SetNewNillableUUID sets the "nillable_uuid" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNillableUUID() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNillableUUID)
	return u
}

// ClearNillableUUID clears the value of the "nillable_uuid" field.
func (u *FieldTypeUpsert) ClearNillableUUID() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNillableUUID)
	return u
}

// SetStrings sets the "strings" field.
func (u *FieldTypeUpsert) SetStrings(v []string) *FieldTypeUpsert {
	u.Set(fieldtype.FieldStrings, v)
	return u
}

// SetNewStrings sets the "strings" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewStrings() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldStrings)
	return u
}

// ClearStrings clears the value of the "strings" field.
func (u *FieldTypeUpsert) ClearStrings() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldStrings)
	return u
}

// SetPair sets the "pair" field.
func (u *FieldTypeUpsert) SetPair(v schema.Pair) *FieldTypeUpsert {
	u.Set(fieldtype.FieldPair, v)
	return u
}

// SetNewPair sets the "pair" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewPair() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldPair)
	return u
}

// SetNilPair sets the "nil_pair" field.
func (u *FieldTypeUpsert) SetNilPair(v *schema.Pair) *FieldTypeUpsert {
	u.Set(fieldtype.FieldNilPair, v)
	return u
}

// SetNewNilPair sets the "nil_pair" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewNilPair() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldNilPair)
	return u
}

// ClearNilPair clears the value of the "nil_pair" field.
func (u *FieldTypeUpsert) ClearNilPair() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldNilPair)
	return u
}

// SetVstring sets the "vstring" field.
func (u *FieldTypeUpsert) SetVstring(v schema.VString) *FieldTypeUpsert {
	u.Set(fieldtype.FieldVstring, v)
	return u
}

// SetNewVstring sets the "vstring" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewVstring() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldVstring)
	return u
}

// SetTriple sets the "triple" field.
func (u *FieldTypeUpsert) SetTriple(v schema.Triple) *FieldTypeUpsert {
	u.Set(fieldtype.FieldTriple, v)
	return u
}

// SetNewTriple sets the "triple" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewTriple() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldTriple)
	return u
}

// SetBigInt sets the "big_int" field.
func (u *FieldTypeUpsert) SetBigInt(v schema.BigInt) *FieldTypeUpsert {
	u.Set(fieldtype.FieldBigInt, v)
	return u
}

// SetNewBigInt sets the "big_int" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewBigInt() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldBigInt)
	return u
}

// ClearBigInt clears the value of the "big_int" field.
func (u *FieldTypeUpsert) ClearBigInt() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldBigInt)
	return u
}

// SetPasswordOther sets the "password_other" field.
func (u *FieldTypeUpsert) SetPasswordOther(v schema.Password) *FieldTypeUpsert {
	u.Set(fieldtype.FieldPasswordOther, v)
	return u
}

// SetNewPasswordOther sets the "password_other" field to the value that was provided on create.
func (u *FieldTypeUpsert) SetNewPasswordOther() *FieldTypeUpsert {
	u.SetExcluded(fieldtype.FieldPasswordOther)
	return u
}

// ClearPasswordOther clears the value of the "password_other" field.
func (u *FieldTypeUpsert) ClearPasswordOther() *FieldTypeUpsert {
	u.SetNull(fieldtype.FieldPasswordOther)
	return u
}

// Update allows overriding fields `UPDATE` values. See the FieldTypeCreate.OnConflict
// documentation for more info.
func (u *FieldTypeUpsertOne) Update(set func(*FieldTypeUpsert)) *FieldTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FieldTypeUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *FieldTypeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FieldTypeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FieldTypeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *FieldTypeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *FieldTypeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// FieldTypeCreateBulk is the builder for creating many FieldType entities in bulk.
type FieldTypeCreateBulk struct {
	config
	builders []*FieldTypeCreate
	conflict []sql.ConflictOption
}

// Save creates the FieldType entities in the database.
func (ftcb *FieldTypeCreateBulk) Save(ctx context.Context) ([]*FieldType, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ftcb.builders))
	nodes := make([]*FieldType, len(ftcb.builders))
	mutators := make([]Mutator, len(ftcb.builders))
	for i := range ftcb.builders {
		func(i int, root context.Context) {
			builder := ftcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FieldTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ftcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ftcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ftcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ftcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ftcb *FieldTypeCreateBulk) SaveX(ctx context.Context) []*FieldType {
	v, err := ftcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ftcb *FieldTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := ftcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ftcb *FieldTypeCreateBulk) ExecX(ctx context.Context) {
	if err := ftcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.FieldType.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UserUpsert) {
//			SetInt(v+v).
//		}).
//      Exec(ctx)
//
func (ftcb *FieldTypeCreateBulk) OnConflict(opts ...sql.ConflictOption) *FieldTypeUpsertBulk {
	ftcb.conflict = opts
	return &FieldTypeUpsertBulk{
		create: ftcb,
	}
}

// FieldTypeUpsertBulk is the builder for "upsert"-ing
//  a bulk of FieldType nodes.
type FieldTypeUpsertBulk struct {
	create *FieldTypeCreateBulk
}

// Update allows overriding fields `UPDATE` values. See the FieldTypeCreateBulk.OnConflict
// documentation for more info.
func (u *FieldTypeUpsertBulk) Update(set func(*FieldTypeUpsert)) *FieldTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&FieldTypeUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *FieldTypeUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the FieldTypeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for FieldTypeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *FieldTypeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
